{
  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems
  #
  # saru is a home NAS with:
  #   - One NVMe boot disk (Samsung MZVL2256, 256GB) declared below.
  #   - Four data disks (sda-sdd) forming the `saru` ZFS pool (2x mirror
  #     vdevs, 2x4TB + 2x14TB). NOT declared here — disko must not touch
  #     them. The pool is imported at boot via `boot.zfs.extraPools` in
  #     configuration.nix.
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = true;
  boot.loader.grub.enable = true;
  disko.devices = {
    disk = {
      main = {
        name = "main-saru-nvme";
        device = "/dev/disk/by-id/nvme-SAMSUNG_MZVL2256HCHQ-00B00_S674NF0R106474";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            "boot" = {
              size = "1M";
              type = "EF02"; # for grub MBR
              priority = 1;
            };
            ESP = {
              type = "EF00";
              size = "500M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" ];
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };
}
